modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "Apache-2.0"

[[mods]]
modId = "grieflogger"
version = "${version}"
displayName = "GriefLogger"
authors = "DAQEM"
description = '''
A mod that logs all player interactions with blocks and entities and stores them in a database.
'''
#logoFile = ""

[[dependencies.grieflogger]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.grieflogger]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.grieflogger]]
modId = "architectury"
mandatory = true
versionRange = "[6.5.85,)"
ordering = "AFTER"
side = "SERVER"

[[dependencies.grieflogger]]
modId = "supermartijn642configlib"
mandatory = true
versionRange = "[${config_library_version},)"
ordering = "NONE"
side = "SERVER"